# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Fast Courier"
client_id = "5141ee570075449f84e5e831ff873ed6"
application_url = "https://wilson-barcelona-colours-located.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_all_orders,read_shipping,write_shipping,read_checkouts,write_checkouts,unauthenticated_read_checkouts,unauthenticated_write_checkouts"

[auth]
redirect_urls = [
  "https://wilson-barcelona-colours-located.trycloudflare.com/auth/callback",
  "https://wilson-barcelona-colours-located.trycloudflare.com/auth/shopify/callback",
  "https://wilson-barcelona-colours-located.trycloudflare.com/api/auth/callback",
  "https://wilson-barcelona-colours-located.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-development-fc-app.myshopify.com"
