# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "15b3d5117ecb43dab6986a0fcabd972d"
name = "Fast Courier"
handle = "fast-courier"
application_url = "https://lopez-steam-inf-doe.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-development-fc-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_all_orders,read_shipping,write_shipping,read_checkouts,write_checkouts,unauthenticated_read_checkouts,unauthenticated_write_checkouts,read_fulfillments,write_fulfillments,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders"

[auth]
redirect_urls = [
  "https://lopez-steam-inf-doe.trycloudflare.com/auth/callback",
  "https://lopez-steam-inf-doe.trycloudflare.com/auth/shopify/callback",
  "https://lopez-steam-inf-doe.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
