# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5141ee570075449f84e5e831ff873ed6"
name = "Fast Courier"
handle = "fc-app-3"
application_url = "https://boundaries-sitemap-dylan-cord.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-development-fc-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_all_orders,read_shipping,write_shipping,read_checkouts,write_checkouts,unauthenticated_read_checkouts,unauthenticated_write_checkouts,read_fulfillments,write_fulfillments,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders"

[auth]
redirect_urls = [
  "https://boundaries-sitemap-dylan-cord.trycloudflare.com/auth/callback",
  "https://boundaries-sitemap-dylan-cord.trycloudflare.com/auth/shopify/callback",
  "https://boundaries-sitemap-dylan-cord.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
